# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:ui}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:8761/eureka/


spring:
  cloud:
    consul:
      host: consul
      discovery:
        hostname: ${HOSTNAME:ui}
        prefer-ip-address: ${PREFER_IP:false}
