# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:ui}
    preferIpAddress: ${PREFER_IP:false}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:${SERVICE_REGISTRY_PORT:8761}/eureka/


spring:
  cloud:
    consul:
      host: consul
      discovery:
        hostname: ${HOSTNAME:ui}
        prefer-ip-address: false
