# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:ui}
  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:registry}:8761/eureka/


spring:
  cloud:
    consul:
      host: consul
      discovery:
        hostname: ${HOSTNAME:ui}
        prefer-ip-address: ${reportportal.discovery.prefer_ip:false}
